spring:
  application:
    name: usian-cart-web
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.18.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    #手动ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    cluster:
      nodes:
        - 192.168.18.135:7001
        - 192.168.18.135:7002
        - 192.168.18.135:7003
        - 192.168.18.135:7004
        - 192.168.18.135:7005
        - 192.168.18.135:7006
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/