server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-cart-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.18.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  redis:
    cluster:
      nodes:
        - 192.168.18.135:7001
        - 192.168.18.135:7002
        - 192.168.18.135:7003
        - 192.168.18.135:7004
        - 192.168.18.135:7005
        - 192.168.18.135:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5