spring:
  application:
    name: usian-item-service11
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.18.135:8066/usian?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    cluster:
      nodes:
        - 192.168.18.135:7001
        - 192.168.18.135:7002
        - 192.168.18.135:7003
        - 192.168.18.135:7004
        - 192.168.18.135:7005
        - 192.168.18.135:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  rabbitmq:
    host: 192.168.18.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    #手动ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.usian.pojo
