server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.18.135:7001
        - 192.168.18.135:7002
        - 192.168.18.135:7003
        - 192.168.18.135:7004
        - 192.168.18.135:7005
        - 192.168.18.135:7006
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
  rabbitmq:
    host: 192.168.18.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true #开启消息确认回调
    publisher-returns: true #开启消息退回回调
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.usian.pojo