spring:
  application:
    name: usian-portal-web
  rabbitmq:
    host: 192.168.18.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/